export const TECH_BRAND_COLORS = {
  "Next.js": "#ffffff",
  "React": "#61DAFB",
  "TypeScript": "#3178C6",
  "Tailwind CSS": "#06B6D4",
  "Three.js": "#ffffff",
  "GSAP": "#88CE02",
  "Framer Motion": "#E10098",
  "Node.js": "#339933",
  "Express.js": "#ffffff",
  "Python": "#3776AB",
  "Golang": "#00ADD8",
  "MongoDB": "#47A248",
  "PostgreSQL": "#4169E1",
  "Prisma": "#2D3748",
  "Redis": "#DC382D",
  "Docker": "#2496ED",
  "Kubernetes": "#326CE5",
  "AWS": "#FF9900",
  "Vercel": "#ffffff",
  "Supabase": "#3ECF8E",
  "Appwrite": "#F02E65",
  "Figma": "#F24E1E",
  "VS Code": "#007ACC",
  "Postman": "#FF6C37",
  "Stripe": "#635BFF",
  "JavaScript": "#F7DF1E",
  "Zod": "#3068b7",
  "Zustand": "#443e38",
  "Java": "#ED8B00",
  "C++": "#00599C",
  "C#": "#239120",
  "PHP": "#777BB4",
  "Ruby": "#CC342D",
  "Go": "#00ADD8",
  "Rust": "#000000",
  "Kotlin": "#7F52FF",
  "Dart": "#0175C2",
  "Angular": "#DD0031",
  "Vue.js": "#4FC08D",
  "Sass": "#CC6699",
  "Django": "#092E20",
  "Laravel": "#FF2D20",
  "Spring Boot": "#6DB33F",
  "FastAPI": "#05998B",
  "Flutter": "#02569B",
  "React Native": "#61DAFB",
  "Swift": "#F05138",
  "Ionic": "#3880FF",
  "Expo": "#000020",
  "MySQL": "#4479A1",
  "Firebase": "#FFCA28",
  "Adobe Photoshop": "#31A8FF",
  "Adobe Illustrator": "#FF9A00",
  "Adobe XD": "#FF61F6",
  "Adobe After Effects": "#CF96FD",
  "Sketch": "#F7B500",
  "Canva": "#00C4CC",
  "Blender": "#F5792A",
  "WebStorm": "#000000",
  "IntelliJ IDEA": "#000000",
  "PyCharm": "#000000",
  "Android Studio": "#3DDC84",
  "Xcode": "#147EFB",
  "Sublime Text": "#FF9800",
  "Vim": "#019733",
  "Git": "#F05032"
};

export const getTechColor = (nameOrId) => {
  // If it's an ID like SiNextdotjs, try to extract the name or map it
  const idToName = {
    "SiNextdotjs": "Next.js",
    "TbBrandNextjs": "Next.js",
    "SiReact": "React",
    "FaReact": "React",
    "SiTypescript": "TypeScript",
    "SiTailwindcss": "Tailwind CSS",
    "SiMongodb": "MongoDB",
    "SiPostgresql": "PostgreSQL",
    "SiPrisma": "Prisma",
    "SiRedis": "Redis",
    "SiDocker": "Docker",
    "SiKubernetes": "Kubernetes",
    "FaAws": "AWS",
    "SiVercel": "Vercel",
    "SiSupabase": "Supabase",
    "SiAppwrite": "Appwrite",
    "SiFigma": "Figma",
    "VscVscode": "VS Code",
    "SiPostman": "Postman",
    "SiStripe": "Stripe",
    "SiJavascript": "JavaScript",
    "SiFramer": "Framer Motion",
    "SiGreensock": "GSAP",
    "SiThreedotjs": "Three.js",
    "FaPython": "Python",
    "SiPython": "Python",
    "FaNodeJs": "Node.js",
    "SiNodedotjs": "Node.js",
    "SiExpress": "Express.js",
    "SiGo": "Go",
    "SiGithubactions": "Git"
  };

  const name = idToName[nameOrId] || nameOrId;
  return TECH_BRAND_COLORS[name] || "#0ea5e9";
};
